<a href="https://colab.research.google.com/github/DeepanshuSharma1607/tech_stuck/blob/main/nlp_proj_l.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
import kagglehub
from kagglehub import KaggleDatasetAdapter

file_path = "all_kindle_review .csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "meetnagadia/amazon-kindle-book-review-for-sentiment-analysis",
  file_path,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

print("First 5 records:", df.head())

/tmp/ipykernel_4365/888148869.py:7: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(


Using Colab cache for faster access to the 'amazon-kindle-book-review-for-sentiment-analysis' dataset.
First 5 records:    Unnamed: 0.1  Unnamed: 0        asin  helpful  rating  \
0             0       11539  B0033UV8HI  [8, 10]       3   
1             1        5957  B002HJV4DE   [1, 1]       5   
2             2        9146  B002ZG96I4   [0, 0]       3   
3             3        7038  B002QHWOEU   [1, 3]       3   
4             4        1776  B001A06VJ8   [0, 1]       4   

                                          reviewText   reviewTime  \
0  Jace Rankin may be short, but he's nothing to ...   09 2, 2010   
1  Great short read.  I didn't want to put it dow...   10 8, 2013   
2  I'll start by saying this is the first of four...  04 11, 2014   
3  Aggie is Angela Lansbury who carries pocketboo...   07 5, 2014   
4  I did not expect this type of book to be in li...  12 31, 2012   

       reviewerID  reviewerName                   summary  unixReviewTime  
0  A3HHXRELK8BHQG        Rid

In [ ]:
df.head()

,Unnamed: 0.1,Unnamed: 0,asin,helpful,rating,reviewText,reviewTime,reviewerID,reviewerName,summary,unixReviewTime
0,0,11539,B0033UV8HI,"[8, 10]",3,"Jace Rankin may be short, but he's nothing to ...","09 2, 2010",A3HHXRELK8BHQG,Ridley,Entertaining But Average,1283385600
1,1,5957,B002HJV4DE,"[1, 1]",5,Great short read. I didn't want to put it dow...,"10 8, 2013",A2RGNZ0TRF578I,Holly Butler,Terrific menage scenes!,1381190400
2,2,9146,B002ZG96I4,"[0, 0]",3,I'll start by saying this is the first of four...,"04 11, 2014",A3S0H2HV6U1I7F,Merissa,Snapdragon Alley,1397174400
3,3,7038,B002QHWOEU,"[1, 3]",3,Aggie is Angela Lansbury who carries pocketboo...,"07 5, 2014",AC4OQW3GZ919J,Cleargrace,very light murder cozy,1404518400
4,4,1776,B001A06VJ8,"[0, 1]",4,I did not expect this type of book to be in li...,"12 31, 2012",A3C9V987IQHOQD,Rjostler,Book,1356912000


In [ ]:
df_d=df[['reviewText','rating']].copy()

In [ ]:
df_d

,reviewText,rating
0,"Jace Rankin may be short, but he's nothing to ...",3
1,Great short read. I didn't want to put it dow...,5
2,I'll start by saying this is the first of four...,3
3,Aggie is Angela Lansbury who carries pocketboo...,3
4,I did not expect this type of book to be in li...,4
...,...,...
11995,Valentine cupid is a vampire- Jena and Ian ano...,4
11996,I have read all seven books in this series. Ap...,5
11997,This book really just wasn't my cuppa. The si...,3
11998,"tried to use it to charge my kindle, it didn't...",1


In [ ]:
df_d.shape

(12000, 2)

In [ ]:
df_d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   reviewText  12000 non-null  object
 1   rating      12000 non-null  int64 
dtypes: int64(1), object(1)
memory usage: 187.6+ KB


In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df_d['rating'].unique()

array([3, 5, 4, 2, 1])

In [ ]:
df_d['rating'].value_counts()

,count
rating,
5,3000
4,3000
3,2000
2,2000
1,2000


In [ ]:
df_d['rating']=df_d['rating'].apply(lambda x:0 if x<3 else 1)

In [ ]:
df_d['rating'].value_counts()

,count
rating,
1,8000
0,4000


In [ ]:
df_d['reviewText']=df_d['reviewText'].str.lower()

In [ ]:
df_d.head()

,reviewText,rating
0,"jace rankin may be short, but he's nothing to ...",1
1,great short read. i didn't want to put it dow...,1
2,i'll start by saying this is the first of four...,1
3,aggie is angela lansbury who carries pocketboo...,1
4,i did not expect this type of book to be in li...,1


In [ ]:
import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
import re
from bs4 import BeautifulSoup

# 1. Remove special characters/keep only alphanumeric
df_d['reviewText'] = df_d['reviewText'].apply(lambda x: re.sub('[^a-z A-Z 0-9]+', ' ', x))

# 2. Remove stopwords (assuming 'stopwords' list is predefined)
df_d['reviewText'] = df_d['reviewText'].apply(lambda x: " ".join([y for y in x.split() if y not in stopwords.words('english')]))

# 3. Remove URLs (http, https, ftp, ssh)
df_d['reviewText'] = df_d['reviewText'].apply(lambda x: re.sub(r'(http|https|ftp|ssh)://([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?', '', x))

# 4. Remove HTML tags using BeautifulSoup
df_d['reviewText'] = df_d['reviewText'].apply(lambda x: BeautifulSoup(x, 'lxml').get_text())

# 5. Remove extra oral spaces
df_d['reviewText'] = df_d['reviewText'].apply(lambda x: " ".join(x.split()))

In [ ]:
df_d.head()

,reviewText,rating
0,jace rankin may short nothing mess man hauled ...,1
1,great short read want put read one sitting sex...,1
2,start saying first four books expecting 34 con...,1
3,aggie angela lansbury carries pocketbooks inst...,1
4,expect type book library pleased find price right,1


In [ ]:
from nltk.stem import WordNetLemmatizer
lem=WordNetLemmatizer()
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [ ]:
def lemmatize(text):
  return " ".join([lem.lemmatize(word) for word in text.split()])

In [ ]:
df_d['reviewText'] = df_d['reviewText'].apply(lambda x: lemmatize(x) )

In [ ]:
df_d.head()

,reviewText,rating
0,jace rankin may short nothing mess man hauled ...,1
1,great short read want put read one sitting sex...,1
2,start saying first four book expecting 34 conc...,1
3,aggie angela lansbury carry pocketbook instead...,1
4,expect type book library pleased find price right,1


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df_d['reviewText'],df_d['rating'],test_size=0.2,random_state=42)

In [ ]:
x_train.shape,y_train.shape,x_test.shape,y_test.shape

((9600,), (9600,), (2400,), (2400,))

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
x_train_b=cv.fit_transform(x_train).toarray()
x_test_b=cv.transform(x_test).toarray()

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
x_train_t=tfidf.fit_transform(x_train).toarray()
x_test_t=tfidf.transform(x_test).toarray()

In [ ]:
x_train_b

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
x_train_t

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
from sklearn.naive_bayes import GaussianNB
nb_model=GaussianNB()
bow=nb_model.fit(x_train_b,y_train)
ttfidf=nb_model.fit(x_train_t,y_train)

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix
y_pred_cv=bow.predict(x_test_b)
y_pred_train_cv=bow.predict(x_train_b)

In [ ]:
y_pred_tf=bow.predict(x_test_t)
y_pred_train_tf=bow.predict(x_train_t)

In [ ]:
print(accuracy_score(y_train,y_pred_train_cv))
print(accuracy_score(y_test,y_pred_cv))

0.8511458333333334
0.6183333333333333


In [ ]:
print(accuracy_score(y_train,y_pred_train_tf))
print(accuracy_score(y_test,y_pred_tf))

0.7909375
0.5725


In [ ]:
confusion_matrix(y_test,y_pred_cv)

array([[ 444,  359],
       [ 557, 1040]])

In [ ]:
confusion_matrix(y_test,y_pred_tf)

array([[490, 313],
       [713, 884]])