<a href="https://colab.research.google.com/github/DeepanshuSharma1607/tech_stuck/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!nvidia-smi

Mon Apr 20 14:29:48 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   42C    P8             11W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
import torch
import pandas as pd
import numpy as np
print(torch.__version__)

2.10.0+cu128


In [ ]:
#tensors  --scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar=torch.tensor([[2, 6],
                      [7, 4],
                      [9, 4]])
scalar

tensor([[2, 6],
        [7, 4],
        [9, 4]])

In [ ]:
scalar.shape

torch.Size([3, 2])

In [ ]:
scalar[0,1]

tensor(6)

In [ ]:
TENSOR=torch.tensor([[[1,2,3],
                      [4,5,6],
                      [7,8,9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
#TENSOR[1]
#NO 2ND MATRIX SO IT WILL GIVE ERROR

In [ ]:
TENSOR=torch.tensor([[[1,2,3],
                      [4,5,6],
                      [7,8,9]],
                       [[11,12,13],
                      [14,15,16],
                      [17,18,19]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([2, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
TENSOR[1]

tensor([[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]])

In [ ]:
#RANDOM TENSORS
rand_tens=torch.rand(3,4)
rand_tens

tensor([[0.0664, 0.6860, 0.1450, 0.5600],
        [0.2590, 0.9520, 0.4343, 0.5007],
        [0.0053, 0.2929, 0.4484, 0.5512]])

In [ ]:
rand_tens.ndim

2

In [ ]:
rand_tens.shape

torch.Size([3, 4])

In [ ]:
rand_tens=torch.rand(2,6,4)

In [ ]:
rand_tens

tensor([[[0.1078, 0.6615, 0.2170, 0.8057],
         [0.5118, 0.2401, 0.7402, 0.3730],
         [0.9941, 0.9120, 0.3392, 0.3906],
         [0.0790, 0.9947, 0.4805, 0.6091],
         [0.2938, 0.1968, 0.3226, 0.8677],
         [0.9598, 0.4920, 0.3547, 0.9584]],

        [[0.4542, 0.1405, 0.9338, 0.9537],
         [0.3533, 0.0968, 0.1566, 0.8813],
         [0.8738, 0.2947, 0.3439, 0.9688],
         [0.9859, 0.5870, 0.5805, 0.9334],
         [0.0131, 0.9093, 0.4229, 0.0593],
         [0.4771, 0.3374, 0.3041, 0.5170]]])

In [ ]:
rand_tens.ndim

3

In [ ]:
rand_tens.shape

torch.Size([2, 6, 4])

In [ ]:
#create a random tensor with similar shape to an image
random_image_size_tensor=torch.rand(size=(3,255,255))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 255, 255]), 3)

In [ ]:
random_image_size_tensor

tensor([[[0.4939, 0.1078, 0.3418,  ..., 0.3854, 0.2663, 0.1448],
         [0.3705, 0.2015, 0.0553,  ..., 0.4138, 0.2963, 0.5191],
         [0.7406, 0.1041, 0.5177,  ..., 0.6444, 0.7478, 0.7075],
         ...,
         [0.0620, 0.2881, 0.2794,  ..., 0.0200, 0.7316, 0.2545],
         [0.0930, 0.5496, 0.8319,  ..., 0.9557, 0.2641, 0.8260],
         [0.6852, 0.8859, 0.7483,  ..., 0.8283, 0.9801, 0.8001]],

        [[0.9763, 0.1988, 0.8681,  ..., 0.7180, 0.2696, 0.2253],
         [0.4182, 0.7583, 0.9711,  ..., 0.7932, 0.7779, 0.2782],
         [0.8124, 0.6135, 0.5484,  ..., 0.3995, 0.6555, 0.9322],
         ...,
         [0.2868, 0.3478, 0.3891,  ..., 0.8222, 0.9009, 0.8293],
         [0.1307, 0.9141, 0.8714,  ..., 0.4892, 0.9364, 0.6727],
         [0.4178, 0.3630, 0.9936,  ..., 0.3311, 0.3828, 0.6469]],

        [[0.0217, 0.0260, 0.8138,  ..., 0.9777, 0.7399, 0.7504],
         [0.0010, 0.7329, 0.5544,  ..., 0.1775, 0.7071, 0.4848],
         [0.5747, 0.9560, 0.4512,  ..., 0.1704, 0.6332, 0.

In [ ]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],dtype=None)
float_32_tensor,float_32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [ ]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                            device=None, # what device is your tensor on
                             dtype=None, # what data type is tesor
                             requires_grad=False #  weather or not to track gradients with tensors operation
                             )
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [ ]:
(float_16_tensor*float_32_tensor).dtype

torch.float32

In [ ]:
int_32_tensor=float_32_tensor.type(torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
(int_32_tensor*float_32_tensor).dtype

torch.float32

In [ ]:
ten=torch.rand(3,4)
ten

tensor([[3.9733e-01, 1.0782e-01, 5.2055e-01, 5.7840e-04],
        [2.4245e-01, 9.7329e-01, 5.2842e-01, 8.2791e-01],
        [8.7195e-01, 6.3285e-01, 5.1613e-01, 6.1030e-01]])

In [ ]:
print("tensor type : ",ten.dtype)
print("tensor shape : ",ten.shape)
print("tensor device: ",ten.device)

tensor type :  torch.float32
tensor shape :  torch.Size([3, 4])
tensor device:  cpu


In [ ]:
###MANIPULATING TENSORS
tens=torch.tensor([1,3,6])
print(tens+10)
print(tens*10)
print(tens-10)
print(tens/10)

tensor([11, 13, 16])
tensor([10, 30, 60])
tensor([-9, -7, -4])
tensor([0.1000, 0.3000, 0.6000])


In [ ]:
print(torch.mul(tens,10))
print(torch.add(tens,10))

tensor([10, 30, 60])
tensor([11, 13, 16])


###MATRIX MULTIPLAICATION
1.Element wise multiplication

2.Dot product



In [ ]:
print("Element  wise multiplication")
print(tens , " * " , tens)
print(tens*tens)

Element  wise multiplication
tensor([1, 3, 6])  *  tensor([1, 3, 6])
tensor([ 1,  9, 36])


In [ ]:
print("Matrix multiplication")
print(torch.matmul(tens,tens))
print(1*1+3*3+6*6)

Matrix multiplication
tensor(46)
46


In [ ]:
tensor_a=torch.rand(3,2)
tensor_b=torch.rand(3,2)
#will give error
print(tensor_a.shape,'\n')
print(tensor_b.shape,'\n')
# print(torch.mm(tensor_a,tensor_b))
# torch.mm == torch.matmul

torch.Size([3, 2]) 

torch.Size([3, 2]) 



In [ ]:
tensor_b.T.shape

torch.Size([2, 3])

In [ ]:
tensor_b=tensor_b.T
print(torch.mm(tensor_a,tensor_b))


tensor([[0.0377, 0.0362, 0.0113],
        [0.1444, 0.2379, 0.0493],
        [0.4237, 0.1094, 0.1089]])


###Finding min,max,mean,sum,etc(tensor)

In [ ]:
x=torch.arange(0,100,10)
x,x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
torch.max(x),x.max()

(tensor(90), tensor(90))

In [ ]:
torch.min(x),x.min()

(tensor(0), tensor(0))

In [ ]:
#torch mean require float32
torch.mean(x,dtype=torch.float32),x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# argmin gives the postition or  index of smallest number
x.argmin()

tensor(0)

In [ ]:
x.argmax()

tensor(9)

## Reshaping stacking ,  squeezing tensors

* Reshaping - Reshape an input tesor
* Stacking - Combine multiple tensors on top of each other vstack and hstack
* Squeez - Remove all `1` dimension from tensor
* Permuate - Return a view of the input with dimensions permuted(swapped)
* View - Return a view of the input tensor of certain shape but keeps the same memory as orignal tensor

In [ ]:
import torch

In [ ]:
x=torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_reshaped=x.reshape(1,9)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
x_reshaped=x.reshape(9,1)
x_reshaped,x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
x=torch.arange(1.,13.)
x,x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [ ]:
x_reshaped=x.reshape(2,6)
x_reshaped,x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
         [ 7.,  8.,  9., 10., 11., 12.]]),
 torch.Size([2, 6]))

In [ ]:
x_reshaped=x.reshape(3,4)
x_reshaped,x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]]),
 torch.Size([3, 4]))

In [ ]:
z=x.view(1,12)
z,z.shape
# change in x will change z and vise versa

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  5., 10., 11., 12.]]),
 torch.Size([1, 12]))

In [ ]:
z[:,0]=5
z,x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  5., 10., 11., 12.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  5., 10., 11., 12.]))

In [ ]:
x_stacked=torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 5.,  5.,  5.,  5.],
        [10., 10., 10., 10.],
        [11., 11., 11., 11.],
        [12., 12., 12., 12.]])

In [ ]:
x_stacked=torch.vstack([x,x,x,x])
x_stacked,x_stacked.shape

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  5., 10., 11., 12.],
         [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  5., 10., 11., 12.],
         [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  5., 10., 11., 12.],
         [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  5., 10., 11., 12.]]),
 torch.Size([4, 12]))

In [ ]:
x_stacked=torch.hstack([x,x,x,x])
x_stacked,x_stacked.shape

(tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  5., 10., 11., 12.,  5.,  2.,
          3.,  4.,  5.,  6.,  7.,  8.,  5., 10., 11., 12.,  5.,  2.,  3.,  4.,
          5.,  6.,  7.,  8.,  5., 10., 11., 12.,  5.,  2.,  3.,  4.,  5.,  6.,
          7.,  8.,  5., 10., 11., 12.]),
 torch.Size([48]))

In [ ]:
x_=torch.rand(1,3)
x_.shape,x_

(torch.Size([1, 3]), tensor([[0.6164, 0.1055, 0.0972]]))

In [ ]:
x_=torch.squeeze(x_)
x_.shape,x_

(torch.Size([3]), tensor([0.6164, 0.1055, 0.0972]))

In [ ]:
x_=torch.unsqueeze(x_,dim=0)
x_.shape,x_

(torch.Size([1, 3]), tensor([[0.6164, 0.1055, 0.0972]]))

In [ ]:
x_=torch.rand(2,1,3)
x_.shape,x_

(torch.Size([2, 1, 3]),
 tensor([[[0.5907, 0.5565, 0.3044]],
 
         [[0.4156, 0.5839, 0.6261]]]))

In [ ]:
x_=torch.squeeze(x_)
x_.shape,x_

(torch.Size([2, 3]),
 tensor([[0.5907, 0.5565, 0.3044],
         [0.4156, 0.5839, 0.6261]]))

In [ ]:
x_=torch.unsqueeze(x_,dim=1)
x_.shape,x_

(torch.Size([2, 1, 3]),
 tensor([[[0.5907, 0.5565, 0.3044]],
 
         [[0.4156, 0.5839, 0.6261]]]))

In [ ]:
x_=torch.rand(1,2,1,2,1,3)
x_.shape,x_

(torch.Size([1, 2, 1, 2, 1, 3]),
 tensor([[[[[[0.7802, 0.5218, 0.7284]],
 
            [[0.5942, 0.1552, 0.3811]]]],
 
 
 
          [[[[0.4801, 0.6714, 0.1125]],
 
            [[0.4804, 0.8807, 0.5360]]]]]]))

In [ ]:
x_=torch.squeeze(x_)
x_.shape,x_

(torch.Size([2, 2, 3]),
 tensor([[[0.7802, 0.5218, 0.7284],
          [0.5942, 0.1552, 0.3811]],
 
         [[0.4801, 0.6714, 0.1125],
          [0.4804, 0.8807, 0.5360]]]))

In [ ]:
x_=torch.unsqueeze(x_,dim=0)
x_.shape,x_

(torch.Size([1, 2, 2, 3]),
 tensor([[[[0.7802, 0.5218, 0.7284],
           [0.5942, 0.1552, 0.3811]],
 
          [[0.4801, 0.6714, 0.1125],
           [0.4804, 0.8807, 0.5360]]]]))

In [ ]:
x_=torch.unsqueeze(x_,dim=2)
x_.shape,x_

(torch.Size([1, 2, 1, 2, 3]),
 tensor([[[[[0.7802, 0.5218, 0.7284],
            [0.5942, 0.1552, 0.3811]]],
 
 
          [[[0.4801, 0.6714, 0.1125],
            [0.4804, 0.8807, 0.5360]]]]]))

In [ ]:
x_=torch.unsqueeze(x_,dim=4)
x_.shape,x_

(torch.Size([1, 2, 1, 2, 1, 3]),
 tensor([[[[[[0.7802, 0.5218, 0.7284]],
 
            [[0.5942, 0.1552, 0.3811]]]],
 
 
 
          [[[[0.4801, 0.6714, 0.1125]],
 
            [[0.4804, 0.8807, 0.5360]]]]]]))

###permute

In [ ]:
x_orig=torch.rand(size=(224,224,3))
# to change the dimensions from one side to another
x_orig.shape

torch.Size([224, 224, 3])

In [ ]:
x_per=x_orig.permute(2,0,1)
x_per.shape

torch.Size([3, 224, 224])

In [ ]:
x_orig=torch.rand(size=(5,6,3))
# to change the dimensions from one side to another
x_orig.shape

torch.Size([5, 6, 3])

In [ ]:
x_per=x_orig.permute(1,2,0)
x_per.shape

torch.Size([6, 3, 5])

In [ ]:
x_orig[0,0,0]=23232

In [ ]:
x_per[0,0,0]

tensor(23232.)